// <auto-generated />
using Metro.Data.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Metro.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.16");

            modelBuilder.Entity("Metro.Data.Entities.Branch", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("Int32");

                    b.Property<string>("ColorHex")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Branches", (string)null);
                });

            modelBuilder.Entity("Metro.Data.Entities.Route", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("Int32");

                    b.Property<int>("FinishStationId")
                        .HasColumnType("Int32");

                    b.Property<double>("Length")
                        .HasColumnType("REAL");

                    b.Property<int>("StartStationId")
                        .HasColumnType("Int32");

                    b.Property<double>("Time")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("FinishStationId");

                    b.HasIndex("StartStationId");

                    b.ToTable("Routes", (string)null);
                });

            modelBuilder.Entity("Metro.Data.Entities.Station", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("Int32");

                    b.Property<int>("BranchId")
                        .HasColumnType("Int32");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.ToTable("Stations", (string)null);
                });

            modelBuilder.Entity("Metro.Data.Entities.Route", b =>
                {
                    b.HasOne("Metro.Data.Entities.Station", "FinishStation")
                        .WithMany()
                        .HasForeignKey("FinishStationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Metro.Data.Entities.Station", "StartStation")
                        .WithMany()
                        .HasForeignKey("StartStationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FinishStation");

                    b.Navigation("StartStation");
                });

            modelBuilder.Entity("Metro.Data.Entities.Station", b =>
                {
                    b.HasOne("Metro.Data.Entities.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Branch");
                });
#pragma warning restore 612, 618
        }
    }
}
